export enum WebSocketEventType {

    SEND_MESSAGE = "SEND_MESSAGE",

    EDIT_MESSAGE = "EDIT_MESSAGE",

    DELETE_MESSAGE = "DELETE_MESSAGE",

    SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST",

    UPDATE_FRIEND_REQUEST = "UPDATE_FRIEND_REQUEST",

    ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST",

    DELETE_FRIEND = "DELETE_FRIEND",

    CREATE_GROUP = "CREATE_GROUP",

    VIEW_MESSAGE = "VIEW_MESSAGE"

}